// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACFZN3bJ6jotL1SURe9fcYPNV1hZp2a3Y',
    appId: '1:554587974674:web:2e1c02af1456ae919ffccb',
    messagingSenderId: '554587974674',
    projectId: 'vpn-app-2d6f9',
    authDomain: 'vpn-app-2d6f9.firebaseapp.com',
    storageBucket: 'vpn-app-2d6f9.firebasestorage.app',
    measurementId: 'G-9VXC6SPSQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVbqsaNILPMY2P2QSZ2vWZZyZl-3ue7vo',
    appId: '1:554587974674:android:b4bf865d6c1303679ffccb',
    messagingSenderId: '554587974674',
    projectId: 'vpn-app-2d6f9',
    storageBucket: 'vpn-app-2d6f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh_n6upIyvvJfXyriTQFEOFBahRyDHs1U',
    appId: '1:554587974674:ios:463f1bad20fb77db9ffccb',
    messagingSenderId: '554587974674',
    projectId: 'vpn-app-2d6f9',
    storageBucket: 'vpn-app-2d6f9.firebasestorage.app',
    iosBundleId: 'com.example.vpnApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh_n6upIyvvJfXyriTQFEOFBahRyDHs1U',
    appId: '1:554587974674:ios:463f1bad20fb77db9ffccb',
    messagingSenderId: '554587974674',
    projectId: 'vpn-app-2d6f9',
    storageBucket: 'vpn-app-2d6f9.firebasestorage.app',
    iosBundleId: 'com.example.vpnApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACFZN3bJ6jotL1SURe9fcYPNV1hZp2a3Y',
    appId: '1:554587974674:web:dc6d71a90df0bdcb9ffccb',
    messagingSenderId: '554587974674',
    projectId: 'vpn-app-2d6f9',
    authDomain: 'vpn-app-2d6f9.firebaseapp.com',
    storageBucket: 'vpn-app-2d6f9.firebasestorage.app',
    measurementId: 'G-QB2DEE3NXQ',
  );
}
